import 'babel-polyfill';
import {testConstants} from './components/constants_ass';
import {testVarScope} from './components/scope_ass';
import {testObjectProps} from './components/enhancedObjectProps';
import {testArrowFunc} from './components/arrowfunc';
import {testExtParameterHandling} from './components/extParameterhandling';
import {testTempLiterals} from './components/temp_literal';
import {testDeStructuringObjects} from './components/de_structure_object';
import {getTotalCashInBank} from './components/class_ass';
import {testSymbol} from './components/symbol_ass';
import {testIterator} from './components/iterator_ass';
import { testGenerator } from './components/generator_ass';
import {testMap_Set} from './components/map_chat_ass';
//testConstants();
//testVarScope();
//testObjectProps();
//testArrowFunc();
//testExtParameterHandling();
//testTempLiterals();
//testDeStructuringObjects();
//getTotalCashInBank();
//testSymbol();
//testIterator();
//testGenerator();
testMap_Set();